# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2017, 3, 22, 19, 36, 47, 183271), max_length=50),
            preserve_default=False,
        ),
    ]
