# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0005_auto_20170322_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
