# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20170326_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comment', to='courses_app.Course'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc_comment', to='courses_app.Description'),
        ),
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_desc', to='courses_app.Course'),
        ),
    ]
