# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20170327_2149'),
        ('courses_app', '0004_auto_20170326_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login_app.User'),
            preserve_default=False,
        ),
    ]
