# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_auto_20170328_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_users',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
