# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62bc1546e87d876398753c8fe950de57256e2bb90de682ace8f132c2ff3ee4d4b22703b778b58465c525eb85f3dcd620e74aae36480acf130c78f59c8bbf0a24

test:
  secret_key_base: 0721dd9d07fac8b948f07724a92ea19d5a23f210ec5814b7eea77433f00012d3c6fc7858413abd868b59fcebab62aec32914a05aba677172ce90063a6a790688

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
